package com.test.SpringBottwithHibernate.Entity;
// Generated May 26, 2020 3:23:43 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeTable generated by hbm2java
 */
@Entity
@Table(name = "employee_table", catalog = "employee_master")
public class EmployeeTable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Override
	public String toString() {
		return "EmployeeTable [id=" + id + ", country=" + country + ", name=" + name + ", phoneno=" + phoneno
				+ ", departmentit=" + departmentit + ", status=" + status + ", createddtm=" + createddtm
				+ ", createdby=" + createdby + ", updateddtm=" + updateddtm + ", uppdatedby=" + uppdatedby
				+ ", getId()=" + getId() + ", getCountry()=" + getCountry() + ", getName()=" + getName()
				+ ", getPhoneno()=" + getPhoneno() + ", getDepartmentit()=" + getDepartmentit() + ", getStatus()="
				+ getStatus() + ", getCreateddtm()=" + getCreateddtm() + ", getCreatedby()=" + getCreatedby()
				+ ", getUpdateddtm()=" + getUpdateddtm() + ", getUppdatedby()=" + getUppdatedby() + ", getClass()="
				+ getClass() + ", hashCode()=" + hashCode() + ", toString()=" + super.toString() + "]";
	}

	private Integer id;
	private Country country;
	private String name;
	private String phoneno;
	private String departmentit;
	private String status;
	private Date createddtm;
	private String createdby;
	private Date updateddtm;
	private String uppdatedby;

	public EmployeeTable() {
	}

	public EmployeeTable(Country country, String name, String phoneno, String departmentit, String status,
			Date createddtm, String createdby, Date updateddtm, String uppdatedby) {
		this.country = country;
		this.name = name;
		this.phoneno = phoneno;
		this.departmentit = departmentit;
		this.status = status;
		this.createddtm = createddtm;
		this.createdby = createdby;
		this.updateddtm = updateddtm;
		this.uppdatedby = uppdatedby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cid", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phoneno", nullable = false, length = 45)
	public String getPhoneno() {
		return this.phoneno;
	}

	public void setPhoneno(String phoneno) {
		this.phoneno = phoneno;
	}

	@Column(name = "departmentit", nullable = false, length = 45)
	public String getDepartmentit() {
		return this.departmentit;
	}

	public void setDepartmentit(String departmentit) {
		this.departmentit = departmentit;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createddtm", nullable = false, length = 19)
	public Date getCreateddtm() {
		return this.createddtm;
	}

	public void setCreateddtm(Date createddtm) {
		this.createddtm = createddtm;
	}

	@Column(name = "createdby", nullable = false, length = 45)
	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateddtm", nullable = false, length = 19)
	public Date getUpdateddtm() {
		return this.updateddtm;
	}

	public void setUpdateddtm(Date updateddtm) {
		this.updateddtm = updateddtm;
	}

	@Column(name = "uppdatedby", nullable = false, length = 45)
	public String getUppdatedby() {
		return this.uppdatedby;
	}

	public void setUppdatedby(String uppdatedby) {
		this.uppdatedby = uppdatedby;
	}

}
